version: '3'
services:
  app-container:
    image: projet_devops_docker:latest # Remplacez par le nom de votre image Docker et sa version/tag
    build:
      context: .
      dockerfile: Dockerfile.nodejs
    ports:
      - "8081:80" # Port mapping, ajustez selon les besoins
    environment:
      NODE_ENV: staging # Environnement de déploiement
    networks:
      - staging_network # Nom du réseau, ajustez si nécessaire

networks:
  staging_network:
    driver: bridge
